---

  - name: install the latest version of Apache
    dnf:
      name: httpd
      state: latest
      
  - name: start httpd
    service: 
      name: httpd 
      state: started



  - name: Create File for Prometheus Systemd
    template:
      src='index.html'
      dest=/var/www/html/index.html
    notify:
      - httpd reload

  - name: ports for httpd
    firewalld:
      port: 80/tcp
      permanent: yes
      state: enabled
    notify:
    - restart firewalld

    
  
...
