version: '3.9'

services:
    db:
        image: postgres:14-alpine
        restart: always
        volumes:
            - ./data/db:/var/lib/postgresql/data
        ports: 
            - 5432:5432
        environment: 
            - POSTGRES_PASSWORD=django
            - POSTGRES_USER=django
            - POSTGRES_DB=django

    backend:
        build:
            context: ./
            dockerfile: Dockerfile_back
        command: python3 manage.py runserver 0.0.0.0:8000
        restart: always
        volumes:
        - ./docker_homework/lib_catalog/:/app/
        # ports: 
        #     - 8000:8000
        environment:
            - POSTGRES_NAME=django
            - POSTGRES_USER=django
            - POSTGRES_PASSWORD=django
            - DATABASE_HOST=db
            - DATABASE_PORT=5432
        depends_on:
            - db

    web:        
        build:
            context: ./
            dockerfile: Dockerfile_web
        restart: always
        volumes:
        - ./docker_homework/frontend/:/web/
        ports:
            - 80:80
        depends_on:
            - backend