---
- hosts: all
  vars:

    # vault password: 1234
    # vault_users_pass: 1q2w3e4r
    password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61623037363363343233303466376136393530366639336266613563326337656562333035393561
          3963373135333662633766616263316666656466333964390a363661366262383937643664613738
          37633265633366373336336133623231306633643831343163333234386138303563383431303537
          3237346637373137610a376262336165346338626438313830303230343234363131326230333939
          3337
  
  tasks:

    - name: create users
      user:
        name: "{{ item.name }}"
        comment: "{{ item.name }}@example.com"
        create_home: True
        password: "{{ item.password | password_hash('sha512') }}"

      loop:
      - name: "Alice"
        password: "{{ password }}"
      - name: "Bob"
        password: "{{ password }}"
      - name: "Carol"
        password: "{{ password }}"
    
...



# Напишите плейбук для создания пользователей Alice, Bob, Carol. 
# Для каждого пользователя нужно задать имя, адрес почты в комментарии (username@example.com), домашнюю папку,
# пароль в зашифрованном виде – в виде зашифрованной переменной или из отдельного шифрованного файла на выбор.
# Кроме пароля больше ничего шифровать не нужно. У уже созданных аккаунтов пароль менять не нужно.


# ansible-playbook playbook01.yaml --ask-vault-pass